# Generated by Django 5.1.7 on 2025-04-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=200)),
                ('movie_name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, help_text='Movie Rating (e.g., 8.5)', max_digits=3)),
            ],
        ),
    ]
